/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thriftclient;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.apache.thrift.TException;

class AppTest {
    @Test
    void isFizz() throws TException {
        assertTrue(App.execFizzOnServer(2).isFizz());
    }

    @Test
    void isBuzz() throws TException {
        assertTrue(App.execFizzOnServer(3).isBuzz());
    }
}
