/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thriftserver;

import org.apache.thrift.server.TServer;
import org.apache.thrift.server.TSimpleServer;
import org.apache.thrift.transport.TServerSocket;
import org.apache.thrift.transport.TServerTransport;
import fizz.shared.FizzBuzzService;

public class App {
    
  public static FizzBuzzServiceImp fizzBuzzServiceImp;

  public static FizzBuzzService.Processor processor;

  public static void main(String [] args) {
    try {
      fizzBuzzServiceImp = new FizzBuzzServiceImp();
      processor = new FizzBuzzService.Processor<FizzBuzzServiceImp>(fizzBuzzServiceImp);

      Runnable simple = new Runnable() {
        public void run() {
          simple(processor);
        }
      };      
     
      new Thread(simple).start();
    } catch (Exception x) {
      x.printStackTrace();
    }
  }

  public static void simple(FizzBuzzService.Processor<FizzBuzzServiceImp> processor) {
    try {
      TServerTransport serverTransport = new TServerSocket(9090);
      TServer server = new TSimpleServer(new TServer.Args(serverTransport).processor(processor));

      System.out.println("Starting the simple server...");
      server.serve();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
