/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package thriftclient;

import org.apache.thrift.TException;
import org.apache.thrift.protocol.TBinaryProtocol;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.transport.TSocket;
import org.apache.thrift.transport.TTransport;

import fizz.shared.FizzBuzzService;
import fizz.shared.FizzDto;

public class App {
    public static void main(String[] args) {

    }

    public static FizzDto execFizzOnServer(int n) {
        FizzDto fizzDto = null ; 

        try {
            TTransport transport;

            transport = new TSocket("localhost", 9090);
            transport.open();

            TProtocol protocol = new TBinaryProtocol(transport);
            FizzBuzzService.Client client = new FizzBuzzService.Client(protocol);

             fizzDto = client.apply(n);

            transport.close();
        } catch (TException x) {
            x.printStackTrace();
        }
        return fizzDto;
    }

}
